[[links]]
name = ".config"
linux = "~"

[[links]]
name = "nvim"
windows = "~/AppData/Local"
linux = "~/.config"

[[links]]
name = ".gitconfig"
windows = "~"
linux = "~"

[[links]]
name = "Microsoft.PowerShell_profile.ps1"
windows = "~/Documents/Powershell"

[[links]]
name = "alacritty.toml"
windows = "~/AppData/Roaming/alacritty"

[[links]]
name = "kipr.omp.json"
windows = "~/.oh-my-posh"
